version: "3.8"
networks:
  network_eth:
    driver: bridge
    name: network_eth_l1
    ipam:
      config:
        - subnet: 172.23.0.0/16

services:
  gateway-store:
    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:v0.7.1
    command:
      - "kv_store"
    ports:
      - "8089:8088"
    restart: unless-stopped

  kms-validator:
    image: ghcr.io/zama-ai/kms-blockchain-asc-dev:v0.7.1
    ports:
      - "36656:26656"
      - "36657:26657"
      - "1317:1317"
      - "9091:9090"
    entrypoint: ["/app/bootstrap.sh"]
    healthcheck:
      test: "wget -Sq --spider http://localhost:26657/status"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  connector:
    image: ghcr.io/zama-ai/kms-blockchain-connector-dev:v0.7.1
    command:
      - "kms-blockchain-connector"
    environment:
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://kms-validator:9091
      - ASC_CONN__CORE__ADDRESSES=http://kms-core:50051
      - ASC_CONN__STORE__URL=http://gateway-store:8089
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__DECRYPTION__RETRY_INTERVAL=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__INITIAL_WAIT_TIME=1
      - ASC_CONN__CORE__TIMEOUT_CONFIG__REENCRYPTION__RETRY_INTERVAL=1
    depends_on:
      kms-validator:
        condition: service_healthy
      kms-core:
        condition: service_healthy
    restart: unless-stopped

  kms-core:
    image: ghcr.io/zama-ai/kms-service-dev:v0.7.1
    ports:
      - "50051:50051"
    healthcheck:
      test: "grpc-health-probe --addr=localhost:50051"
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  gateway:
    image: ghcr.io/zama-ai/kms-blockchain-gateway-dev:v0.7.1
    ports:
      - "7077:7077"
    command:
      - "gateway"
    volumes:
      - ./default.toml:/app/gateway/config/default.toml:Z
    environment:
      - GATEWAY__ETHEREUM__LISTENER_TYPE=FHEVM_V1_1
      - GATEWAY__ETHEREUM__WSS_URL=ws://geth:8546
      - GATEWAY__ETHEREUM__HTTP_URL=http://geth:8545
      - GATEWAY__ETHEREUM__FHE_LIB_ADDRESS=000000000000000000000000000000000000005d
      - GATEWAY__ETHEREUM__ORACLE_PREDEPLOY_ADDRESS=c8c9303Cd7F337fab769686B593B87DC3403E0ce
      - GATEWAY__KMS__ADDRESS=http://kms-validator:9091
      - GATEWAY__KMS__KEY_ID=408d8cbaa51dece7f782fe04ba0b1c1d017b1088
      - GATEWAY__STORAGE__URL=http://gateway-store:8089
      - ASC_CONN__BLOCKCHAIN__ADDRESSES=http://kms-validator:9091
      - GATEWAY__ETHEREUM__RELAYER_KEY=7ec931411ad75a7c201469a385d6f18a325d4923f9f213bd882bbea87e160b67
      - RUST_BACKTRACE=1
    depends_on:
      geth:
        condition: service_healthy
      kms-validator:
        condition: service_healthy
    restart: unless-stopped

  geth:
    networks:
      network_eth:
        ipv4_address: 172.23.0.2
    environment:
      - TFHE_EXECUTOR_CONTRACT_ADDRESS=0x05fD9B5EFE0a996095f42Ed7e77c390810CF660c
      - FHEVM_GO_KEYS_DIR=/network-fhe-keys
    ports:
      - "8545-8546:8545-8546"
    image: encifher-geth:geth
    command:
      - --networkid=9000
      - --state.scheme=path
      - --verbosity=3
      - --datadir=/execution-data
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=admin,engine,net,eth,web3,debug,txpool,personal
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,engine,net,eth,web3,debug,txpool,personal
      - --ws.origins=*
      - --allow-insecure-unlock
      - --nat=extip:172.23.0.2
      - --authrpc.port=8551
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      - --syncmode=full
      - --gcmode=archive
      - --rpc.allow-unprotected-txs
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=9001
      - --discovery.port=30303
      - --port=30303
    volumes:
      - ./data/execution-data:/execution-data
      - ./genesis_data/el-cl-genesis-data:/el-cl-genesis-data
      - ./network-fhe-keys:/network-fhe-keys:Z
      - ./setup.sh:/config/setup.sh:Z
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: 'curl -s -H "Connection: Upgrade" -H "Upgrade: websocket"  http://localhost:8546'
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  beacon:
    networks:
      - network_eth
    image: sigp/lighthouse:latest-unstable
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --disable-enr-auto-update
      - --enr-address=172.23.0.3
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --listen-address=0.0.0.0
      - --port=9000
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --http-allow-sync-stalled
      - --slots-per-restore-point=32
      - --disable-packet-filter
      - --execution-endpoints=http://geth:8551
      - --jwt-secrets=/el-cl-genesis-data/jwt/jwtsecret
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --subscribe-all-subnets
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --enable-private-discovery
      - --testnet-dir=/el-cl-genesis-data/network-configs
    volumes:
      - ./data/consensus-data:/consensus-data
      - ./genesis_data/el-cl-genesis-data:/el-cl-genesis-data
    depends_on:
      - geth
    restart: unless-stopped

  validator:
    networks:
      network_eth:
        ipv4_address: 172.23.0.4
    image: sigp/lighthouse:latest-unstable
    command:
      - lighthouse
      - vc
      - --debug-level=info
      - --testnet-dir=/network-configs
      - --validators-dir=/validator-keys/keys
      - --secrets-dir=/validator-keys/secrets
      - --init-slashing-protection
      - --beacon-nodes=http://beacon:4000
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=8080
    volumes:
      - ./genesis_data/el-cl-genesis-data/network-configs:/network-configs
      - ./genesis_data/validator-keys:/validator-keys
    depends_on:
      - beacon
    restart: unless-stopped
